server:
  port: 8089

spring:
  application:
    name: dubbo-demo-consumer
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
dubbo:
  scan:
    base-packages: com.g170.dubbo.demo.consumer
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
